name: stale repo identifier and archive

on:
  workflow_dispatch:

jobs:
  identify-stale:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30

    - name: Save stale_repos.json as artifact
      uses: actions/upload-artifact@v2
      with:
        name: stale-repos
        path: stale_repos.json

  archive-repos:
    name: Archive Stale Repositories
    runs-on: ubuntu-latest
    needs: identify-stale

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download stale_repos.json artifact
      uses: actions/download-artifact@v2
      with:
        name: stale-repos
        path: .

    - name: Read URLs from stale_repos.json
      run: |
        jq -r '.[] | .url' stale_repos.json > urls.txt
        cat urls.txt
      
    - name: Archive repositories
      run: |
        while IFS= read -r url; do
          gh repo archive -y "$url"
        done < urls.txt
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
