name: Stale Repos

on:
  workflow_dispatch:

jobs:
  identify-stale:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    outputs: 
      repos: ${{steps.print-stale.outputs.url}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30
        EXEMPT_TOPICS: "archive-false"
        
    - name: Print output of stale_repos tool
      id: print-stale
      run: |
        {
        echo 'url<<EOF'
        jq -r '.[] | .url' stale_repos.json
        echo EOF
        } >> $GITHUB_OUTPUT
        cat stale_repos.md >> $GITHUB_STEP_SUMMARY

    - name: Generate dynamic artifact name
      id: generate-name
      run: echo "ARTIFACT_NAME=stale-repos-$(date +'%Y-%m-%d')-.json" >> $GITHUB_ENV

    - name: Save JSON file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: stale_repos.json
        
    - name: Archive repositories 
      run: |
        echo "${{needs.identify-stale.outputs.repos}}" > urls.txt
        while IFS= read -r url; do
          gh repo archive -y "$url"
        done < urls.txt  
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
