name: Stale Repos v2

on:
  workflow_dispatch:

jobs:
  identify-stale:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    outputs: 
      repos: ${{steps.print-stale.outputs.url}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30
        EXEMPT_TOPICS: 'archive-false'
        
    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        token: ${{ secrets.ARCHIVE }}
