name: stale repo identifier

on:
  workflow_dispatch:
  
jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30

    - name: Print output of stale_repos tool
      run: |
        cat stale_repos.json
        jq -r '.[] | .url' stale_repos.json > urls.txt
        cat urls.txt
