name: Stale Repos

on:
  workflow_dispatch:

jobs:
  identify-stale:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    outputs: 
      repos: ${{steps.print-stale.outputs.url}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30
        
    - name: Print output of stale_repos tool
      id: print-stale
      run: |
        {
        echo 'url<<EOF'
        jq -r '.[] | .url' stale_repos.json
        echo EOF
        } >> $GITHUB_OUTPUT

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: stale_repos.md
        token: ${{ secrets.ARCHIVE }}
        
    - name: Generate dynamic artifact name
      id: generate-name
      run: echo "ARTIFACT_NAME=$(date +'%Y-%m-%d-%H-%M-%S')-stale-repos.json" >> $GITHUB_ENV

    - name: Save JSON file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: path/to/stale_repos.json
        
  archive-repos:
    name: Archive Stale Repositories
    runs-on: ubuntu-latest
    needs: identify-stale

    steps:
    - name: Archive repositories 
      run: |
        echo "${{needs.identify-stale.outputs.repos}}" > urls.txt
        while IFS= read -r url; do
          gh repo archive -y "$url"
        done < urls.txt
        
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
