name: Stale Repos

on:
  workflow_dispatch:

jobs:
  identify-stale:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    outputs: 
      repos: ${{steps.print-stale.outputs.url}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30
        
    - name: Print output of stale_repos tool
      id: print-stale
      run: |
        {
        echo 'url<<EOF'
        jq -r '.[] | .url' stale_repos.json
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: toJSON(./stale_repos.json)
        token: ${{ secrets.ARCHIVE }}
        
  #archive-repos:
 #   name: Archive Stale Repositories
 #   runs-on: ubuntu-latest
 #   needs: identify-stale

  #  steps:
   # - name: Archive repositories 
    #  run: |
     #   ${{needs.identify-stale.outputs.repos}} > urls.txt
      #  while IFS= read -r url; do
       #   gh repo archive -y "$url"
        #done < urls.txt
        
      #env:
       # GH_TOKEN: ${{ secrets.ARCHIVE }}

