name: stale repo identifier and archive

on:
  workflow_dispatch:
  
jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ARCHIVE }}
        INACTIVE_DAYS: 30

    - name: Print output of stale_repos tool
      run: |
        jq -r '.[] | .url' stale_repos.json > urls.txt
        cat urls.txt

  archive:
    name: Archive Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Read URLs from file
        id: read-urls
        run: |
          mapfile -t urls < urls.txt
          echo "::set-output name=urls::${urls[*]}"
      
      - name: Archive repositories
        run: |
          for url in "${{ steps.read-urls.outputs.urls }}"; do
            gh repo archive -y "$url"
          done
        env:
          GH_TOKEN: ${{ secrets.ARCHIVE }}
