name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')  && contains(github.event.pull_request.labels.*.name, 'bug') # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
      - name: Continue
        if: contains(github.event.comment.body, '/continue')   # check the comment if it contains the keywords
        run: |
          echo ${{ github.event.pull_request.body }}
